### ISSUE TITLE
[CircularUI] [EntryPopup && TwoButtonPage] Issues

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#81] opened 2018-07-24 10:39 UTC
I found two problems one with EntryPopup and one with TwoButtonPage.

Description:

I attach simple application showing two problems , one with EntryPopup , and one with left and right buttons in TwoButtonPage. Both are Tizen.Wearable.CircularUI.Forms components.

1# EntryPopup

Text color changes to "white" after initializing Text attribute from view model. To obtain this in my application just write something in entry , go to previous page , and again go to EntryPopup page. Text only have good color while focused , but despite that it's white.

2#TwoButtonPage.

Can not change icon attribute in runtime. Button at left is changing Icon attribute of the button at right. In TwoButton.xaml there is commented code, because I was testing it in two ways:

a) binding Icon to property and then changing property by doing OnPropertyChanged

b) changing Icon in Code Behind file by creating an event

Both do not work , Icon is not changing at right button.

**See issue and application at: TNEXT-16153**

**Comment by jkpu** [comment] 2018-08-09 01:58
1#.  I can't understand what is issue exactly. please attach screenshot image and your code(which text color had change "white"). and what you mean this sentence?  "Text only have good color while focused , but despite that it's white."

2#. I have encountered error when I extract file that is attached in TNEXT-16153, please attach screenshot for clarifying the issue.

**Comment by jsobczuk** [comment] 2018-08-09 10:43
I uploaded .zip version of application at : TNEXT-16153

Ok, thanks for resolving the Icon issue.

After you launch application (GoToEntryPopupPage) , just type something into entry, then leave the page and come back.
Text color is chaning to white even though property is set in XAML file.

Same thing happens when I would add a button on this page , that click would change EntryPopup "IsPassword" property. After changed to IsPassword=true , text also changes to white.

**Comment by jkpu** [comment] 2018-08-29 06:49
I can't reproduce PopupEntry issue with BUG_EntryPopup_TextColor tpk .
I reproduce step is : launch app -> tap Go to EntryPopupPage -> type something into entry -> back key -> main page -> tap Go to  EntryPopupPage -> PopupEntry keep previous typed charactor and color is blue . 

I check with 4.0 emulator and Solis target . 
( emul : Build=tizen-4.0-unified_20180728.1 , solis Build=DayR765KO40_20180716.001 )

**Comment by jkpu** [comment] 2018-08-29 07:01
attached project code : http://suprem.sec.samsung.net/jira/browse/TNEXT-16153
reproduce step : launch app ->  Go to EntryPopupPage -> type something -> back key -> Go to EntryPopupPage -> typed charactor are display but color is changed.

**Comment by idkiller** [comment] 2018-09-03 07:12
This issue looks resolved in PR #108

**Closed by idkiller** 2018-09-03 07:12 UTC
