### ISSUE TITLE
Rotating emulator while PopupEntry in edit mode closes edit mode and prevents reentry.

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#254] opened 2020-03-07 20:39 UTC
**Describe the bug**
While running in emulator, while `PopupEntry` is in activly edit mode, if rotating emulator the edit mode will be closed and you will not be able to reenter edit mode until closing and restarting the emulator.

**To Reproduce**
1. Create page with a `PopupEntry`
2. Select `PopupEntry` and enter edit mode
3. Rotate emulator at least once in any manner or direction
4. Observe `PopupEntry` edit mode has closed and you cannot reentrer it again

**Expected behavior**
Its expected that rotating the emulator does not effect the running application nor leave the program in a less usable state

**Environment:**
    Target Product Emulator 4.0 Release on 3.6 SDK (2.8.0.24)
    Tizen Platform Version [Tizen 4.0.0]
    Tizen.CircularUI Version [1.4.0]

**Comment by jkpu** [comment] 2020-03-10 01:45
This issue is same as https://github.com/Samsung/Tizen.CircularUI/issues/127

I can't reproduce this issue(input method doesn't display until emulator reboot) with your sequence (rotating emulator )
but, I easily reproduced the issue with PC keybord. For example, Press Enter key in  PC keybord when Edit Popup is displaying, and then Edit Popup is never displayed until emulator reboot.
I can't reproduce this issue in real device(e.g GalaxyWatch) because real device doesn't support rotating and keybord input. as you can see in #127 , this issue is same as many inhouse app.
This issue can not be handled by CircularUI side, This issue is emulator Input method issue .
So I closed this issue.

**Closed by jkpu** 2020-03-10 01:45 UTC
Labels: bug

**Comment by axa88** [comment] 2020-03-10 17:10
is there any repository to report emulator issues?

**Comment by jkpu** [comment] 2020-03-11 01:11
Emualtor and Tool git is not public git. so I raise this issue in  internal git.
